################################################
#                                              #
#                  Timed Fly                   #
#               Made by By_Jack                #
#                                              #
################################################

# Use 'none' to disable
Prefix: '&cTimedFly >> '

# Cooldown time to get more flight time,use s for seconds, m for minutes
# and h for hours
Cooldown: 1h

# Type: sqlite for flatfile or mysql for an external database.
Type: 'sqlite'
# Only edit if 'mysql' is set in Type
MySQL:
  # name of your database
  Database: 'test'
  # ip of you MySQL database
  Host: 'localhost'
  # port of you MySQL database, commonly is 3306
  Port: 3306
  # username of you MySQL database
  Username: 'user'
  # password of you MySQL database
  Password: 'root'

# Custom command to open the Timed Fly menu, for multiple commands use ';' (example below)
OpenMenuCommand: 'fly;flymenu'

Gui:
  Enable: true
  # Custom name of the inventory
  DisplayName: TimedFly
  # Rows of the inventory (must be multiple of 9, ex: 9, 18... etc)
  Slots: 9

# If true the players time will be saved with the player leaves the server
StopTimerOnLeave: true

# If true flight will be disabled for 10 seconds if the player attacks a mob/player.
StopFlyOnAttack: true

# If true flight will be disabled if the player is on the ground.
StopFlyOnGround: false

# If true the players time will be saved with the player enters one of the blacklisted worlds
# Do not use if you are running the plugin with multiple servers liked via MySQL
StopTimerOnBlackListedWorld: false

# If true players with "timedfly.fly.onoff" will not be able to get/buy time.
SkipFlightTimeIfHasPerm: true

# Att: This is still on beta
# If true a bossbar will appear when a player buys time (only servers v1.9 and above)
BossBarTimer:
  Enabled: false
  Color: green
  Style: SEGMENTED_6

# If true player will join flying if the have some time left
JoinFlying:
  Enabled: true
  Height: 2

# Set to false if you are lazy and you are using spigot 1.8
Sounds:
  Enabled: true
  Announcer: ENTITY_EXPERIENCE_ORB_PICKUP
  FlightDisabled: ENTITY_WITHER_DEATH

# If true the currency used will be from TokenManager, balance placeholder: %tokens%
UseTokenManager: false

# If true the currency used will be from Vault, balance placeholder: %balance%
UseVault: true

# If true players will be charged from their exp levels
UseLevelsCurrency: false

# If true players will be charged from their experience points
UseExpCurrency: false

# If true players with timedfly.fly.onof will enable fly mode when using one of the custom cmds
FlyModeIfHasPerm: true

# If set to true players will need a permission to use the command /fly
UsePermission:
  Use: false
  Permission: 'timedfly.flygui'

# This is the limit amount of time a player can add to his fly time (in minutes)
# bypass this with timedfly.limit.bypass.
LimitMaxTime: 30

# Announce the time left chosen below to the player (time in seconds)
Announcer:
  Chat: false
  Titles: true
  Times:
  - '120'
  - '60'
  - '10'
  - '5'
  - '4'
  - '3'
  - '2'
  - '1'
  - '0'

# Display some messages on Title/Actionbar.
Messages:
  Title: true
  ActionBar: true

# If true it will execute a command when flight disables
OnFlyDisableCommands:
  Enabled: false
  Commands:
  - '[console] say %player% is using hacks D:'
  - '[player] say i''m using hacks >:D'

# A list of world in which you want the plugin to be enabled.
World-List:
  # Available types:
  # enabled: the plugin will work in worlds listed
  # disabled: the plugin will not work in worlds listed
  # all: the plugin will work in all worlds
  Type: 'all'
  Worlds:
  - 'world'
  - 'survival'

# If the server is running aSkyBlock and this is true players flight will be disabled when exiting the island
ASkyblockIntegration: true

# The name says it...
Check-For-Updates: true
# Auto download new updates
Auto-Download: false

# Choose your own message file (if file name is lang_en.yml use the work after lang_ in this case will be en
# Current languages es, sp, hu, de, you can create your own and send it to me so I added for default.
# Is not recommended to use the /tf reload command, some messages will not change.
Lang: en
